export const FILTER_MENU = 'FILTER_MENU';
export const PORTFOLIOS_BEST_LIST = 'PORTFOLIOS_BEST_LIST';
export const PORTFOLIOS_PAGINATION_LIST = 'PORTFOLIOS_PAGINATION_LIST';
export const PORTFOLIOS_CUSTOM_POPUP = 'PORTFOLIOS_CUSTOM_POPUP';
export const PORTFOLIOS_CATEGORY_LIST = 'PORTFOLIOS_CATEGORY_LIST';
export const PORTFOLIOS_FILTER = 'PORTFOLIOS_FILTER';
export const PORTFOLIOS_MY_LIST = 'PORTFOLIOS_MY_LIST';
export const PORTFOLIOS_I_FOLLOW_LIST = 'PORTFOLIOS_I_FOLLOW_LIST';
export const FOLLOW_ME_PAGINATION_LIST = 'FOLLOW_ME_PAGINATION_LIST';
export const FOLLOW_ME_LIST = 'FOLLOW_ME_LIST';
export const CREATE_OR_EDIT_PORTFOLIO = 'CREATE_OR_EDIT_PORTFOLIO';
export const PERFORMANCE_DATA = 'PERFORMANCE_DATA';
export const MANAGE_UNFOLLOW_PORTFOLIO_POPUP =
  'MANAGE_UNFOLLOW_PORTFOLIO_POPUP';
export const MANAGE_BROKER_LOGIN_POPUP = 'MANAGE_BROKER_LOGIN_POPUP';
export const SET_SOCKET_ASSET_PRICE_DATA = 'SET_SOCKET_ASSET_PRICE_DATA';
